title: Miao Di
# logo: assets/img/photo.jpeg
description: Personal Page.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

links:
  - title: LinkedIn
    url: www.linkedin.com/in/di-miao-855468224

github:
  is_project_page: false
  is_user_page: true
